<a href="https://colab.research.google.com/github/pawelc/Advances-in-Financial-Machine-Learning/blob/main/Chapter_2_Financial_Data_Structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
from IPython import display

In [56]:
def pcaWeights(cov, riskDist=None, riskTarget = 1.):
  eVal, eVec = np.linalg.eigh(covariance)
  print(f"eVal=\n{eVal}") 
  print(f"eVec=\n{eVec}") 
  indices = eVal.argsort()[::-1]
  print(f"indices=\n{indices}") 
  eVal, eVec = eVal[indices], eVec[:,indices]
  print(f"sorted eVal=\n{eVal}") 
  print(f"sorted eVec=\n{eVec}")
  if riskDist is None:
    riskDist = np.zeros(covariance.shape[0])
    riskDist[-1] = 1.0
  loads = riskTarget*(riskDist/eVal)**.5
  wghts = np.dot(eVec, np.reshape(loads, (-1, 1)))
  return wghts

In [57]:
from numpy.matrixlib.defmatrix import N
np.random.seed(200)
dim = 4
L = np.tril(np.random.normal(loc=0, scale=1, size=(dim,dim))) 
riskDist = None
riskTarget = 1. 

print(f"L=\n{L}") 
covariance = L @ L.transpose()
print(f"covariance=\n{covariance}") 

pcaWeights(covariance)

L=
[[-1.45094825  0.          0.          0.        ]
 [ 0.36146623 -0.03294967  0.          0.        ]
 [-0.69193937  0.79200593  0.07324913  0.        ]
 [ 0.21348149  1.01734895  1.91171178 -0.52967163]]
covariance=
[[ 2.10525082 -0.5244688   1.00396822 -0.30975059]
 [-0.5244688   0.13174352 -0.27620906  0.04364504]
 [ 1.00396822 -0.27620906  1.11141893  0.79806139]
 [-0.30975059  0.04364504  0.79806139  5.01576721]]
eVal=
[6.89211546e-07 3.38489771e-01 2.84873342e+00 5.17695659e+00]
eVec=
[[ 0.2222101  -0.49153754  0.8410908  -0.03974638]
 [ 0.974074    0.07486897 -0.21346571  0.00261995]
 [ 0.04242926  0.8491483   0.49367705  0.18283841]
 [-0.00150424 -0.17813657 -0.05728545  0.98233572]]
indices=
[3 2 1 0]
sorted eVal=
[5.17695659e+00 2.84873342e+00 3.38489771e-01 6.89211546e-07]
sorted eVec=
[[-0.03974638  0.8410908  -0.49153754  0.2222101 ]
 [ 0.00261995 -0.21346571  0.07486897  0.974074  ]
 [ 0.18283841  0.49367705  0.8491483   0.04242926]
 [ 0.98233572 -0.05728545 -0.1781365

array([[ 267.66250132],
       [1173.31785754],
       [  51.10803731],
       [  -1.81193314]])

In [53]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])